### ISSUE TITLE
Error when subscription is deleted

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh_auth#9]
I noticed the following error in the logs when a subscription is deleted:
```
Traceback (most recent call last):
--
  | File "/usr/src/app/userauth/views.py", line 60, in webhook
  | on_customer_subscription_deleted(request, event)
  | File "/usr/src/app/userauth/views.py", line 83, in on_customer_subscription_deleted
  | user, created = get_or_create_user_for_stripe_event_object(obj)
  | File "/usr/src/app/userauth/views.py", line 91, in get_or_create_user_for_stripe_event_object
  | if not customer.email:
  | File "/usr/local/lib/python3.8/site-packages/stripe/stripe_object.py", line 92, in __getattr__
  | raise AttributeError(*err.args)
AttributeError: email
```
This error is because the code expects the customer to have an email.

**Comment by johnbradley** [comment]
I think the problem is because this customer was deleted.
https://stripe.com/docs/api/customers/retrieve
> If it’s for a deleted Customer, a subset of the customer’s information is returned, including a deleted property that’s set to true.

We are using the email address to lookup the user to deactivate them.
It looks like we will need a way to lookup a user from their stripe customer id.
